name: "Test github-actions"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./yarn-install
      with:
        npm-token: ${{ secrets.NPM_TOKEN }}
    - run: yarn lint
    - run: yarn test
